version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: admin
      REDIS_DB: 0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin
